### ISSUE TITLE
Improper naming convention

### ISSUE THREAD

**Issue by MonsterAzi** [Ivo-Balbaert/The_Way_to_Mojo#1]
In §3.5 on Typing in Mojo, this is stated:

> Finally, here is a naming convention:
> 
> - variable and function names start with a lowercase letter, and follow camelCase style (example: luckyNumber).
> - types (like Int) start with an uppercase letter, and follow PascalCase style (example: IntPair).

While the recommendation on types is correct, the recommendation of variable and function names does not follow PEP 8:

> Function and Variable Names
> --------------------------------
> 
> Function names should be lowercase, with words separated by underscores as necessary to improve readability.
> 
> Variable names follow the same convention as function names.
> 
> mixedCase is allowed only in contexts where that’s already the prevailing style (e.g. threading.py), to retain backwards compatibility.

Mojo is based on Python syntax, so I think giving advice in line with the PEPs may be beneficial.

**Comment by Ivo-Balbaert** [comment]
I have changed the text to reflect PEP 8. Thanks for reporting this!
